apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: control-plane-operator
  template:
    metadata:
      labels:
        name: control-plane-operator
    spec:
      serviceAccountName: control-plane-operator
      containers:
      - name: control-plane-operator
        image: {{ .ControlPlaneOperatorImage }}
        imagePullPolicy: Always
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/usr/bin/control-plane-operator"]
        args: ["run", "--namespace", "$(MY_NAMESPACE)", "--deployment-name", "control-plane-operator"]
