apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hypershift
  name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator
  template:
    metadata:
      labels:
        name: operator
    spec:
      serviceAccountName: operator
      containers:
      - name: operator
        image: hypershift:latest
        imagePullPolicy: Always
        command:
        - /usr/bin/hypershift-operator
        args:
        - run
