apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: hypershift-operator
rules:
- apiGroups:
  - hypershift.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  - controlplane.cluster.x-k8s.io
  - infrastructure.cluster.x-k8s.io
  - machines.cluster.x-k8s.io
  - exp.infrastructure.cluster.x-k8s.io
  - addons.cluster.x-k8s.io
  - exp.cluster.x-k8s.io
  - cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  - pods
  - secrets
  - nodes
  - namespaces
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
