apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosted-cluster-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hosted-cluster-config-operator
  template:
    metadata:
      labels:
        app: hosted-cluster-config-operator
        clusterID: "{{ .ClusterID }}"
{{ if .RestartDate }}
      annotations:
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: clusterID
                      operator: In
                      values: ["{{ .ClusterID }}"]
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
{{ if .MasterPriorityClass }}
      priorityClassName: {{ .MasterPriorityClass }}
{{ end }}
      containers:
      - image: {{ .HostedClusterConfigOperatorImage }}
        name: hosted-cluster-config-operator
{{ if .HostedClusterConfigOperatorSecurity }}
        securityContext:
          runAsUser: {{ .HostedClusterConfigOperatorSecurity }}
{{ end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENSHIFT_RELEASE_VERSION
          value: {{ version "release" }}
        - name: KUBERNETES_VERSION
          value: {{ version "kubernetes" }}
        command:
        - "/usr/bin/hosted-cluster-config-operator"
        - "--initial-ca-file=/etc/kubernetes/config/initial-ca.crt"
        - "--target-kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig"
        - "--namespace"
        - "$(POD_NAMESPACE)"{{range $controller := .HostedClusterConfigOperatorControllers }}
        - "--controllers={{$controller}}"{{end}}
{{ if .HostedClusterConfigOperatorResources }}
        resources:{{ range .HostedClusterConfigOperatorResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ range .ResourceLimit }}
          limits: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{ end }}
        volumeMounts:
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
        - mountPath: /etc/kubernetes/config
          name: config
      restartPolicy: Always
      serviceAccountName: hosted-cluster-config-operator
      volumes:
      - name: kubeconfig
        secret:
          secretName: service-network-admin-kubeconfig
      - name: config
        configMap:
          name: hosted-cluster-config-operator
