apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  labels:
    app: cluster-autoscaler
spec:
  selector:
    matchLabels:
      app: cluster-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.20.0
          name: cluster-autoscaler
          volumeMounts:
            - name: target-kubeconfig
              mountPath: /mnt/kubeconfig
          command:
            - /cluster-autoscaler
          args:
            - --cloud-provider=clusterapi
            - --node-group-auto-discovery=clusterapi:namespace={{ .Namespace }}
            - --kubeconfig=/mnt/kubeconfig/target-kubeconfig
            - --clusterapi-cloud-config-authoritative
            - --alsologtostderr
            - --v=4
      serviceAccountName: cluster-autoscaler
      terminationGracePeriodSeconds: 10
      volumes:
        - name: target-kubeconfig
          secret:
            secretName: admin-kubeconfig
            items:
              - key: value
                path: target-kubeconfig
